name: CI/CD to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: davletkulov
      DOCKERHUB_PASSWORD: fuV)aUh8V+^3?m8

    steps: 
      - name: Check out the repo 
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: Dockerfile
          push: true
          tags: davletkulov/accountant-client:latest